In [1]:
import sqlalchemy as sa
import pandas as pd

In [2]:
def read_sql_data_frame(path):
    engine = sa.create_engine("sqlite:///%s" % path)
    connection = engine.connect()

    return pd.read_sql("experiments", connection)

In [9]:
df = read_sql_data_frame('../data/without_gambler/the_main.db')

In [10]:
df.describe()

,exp_index,first_opponent_q_1,first_opponent_q_2,first_opponent_q_3,first_opponent_q_4,second_opponent_q_1,second_opponent_q_2,second_opponent_q_3,second_opponent_q_4,mem_one_p_1,...,mem_one_cycle_length,reactive_p_1,reactive_p_2,reactive_p_3,reactive_p_4,evol_reactive_p_1,evol_reactive_p_2,evol_reactive_p_3,evol_reactive_p_4,reactive_cycle_length
count,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,...,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000
mean,699.500000,0.489007,0.507402,0.502601,0.499320,0.530785,0.489808,0.512000,0.496100,0.279421,...,4.745000,0.060185,0.100258,0.060185,0.100258,0.054179,0.025650,0.054179,0.025650,1.341667
std,173.349358,0.290455,0.292337,0.280937,0.289866,0.295137,0.280315,0.289884,0.293641,0.417295,...,68.969786,0.233841,0.225164,0.233841,0.225164,0.224799,0.090073,0.224799,0.090073,4.768245
min,400.000000,0.001186,0.002370,0.000538,0.001145,0.000254,0.001949,0.002366,0.000720,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,549.750000,0.225239,0.251069,0.271933,0.254379,0.269645,0.264528,0.250745,0.254005,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,699.500000,0.492573,0.522296,0.500685,0.480495,0.534369,0.476689,0.525786,0.487515,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,849.250000,0.730447,0.760044,0.752298,0.769010,0.798801,0.718839,0.754344,0.760176,0.641146,...,2.000000,0.000000,0.026905,0.000000,0.026905,0.000000,0.000000,0.000000,0.000000,1.000000
max,999.000000,0.998462,0.998575,0.996398,0.999766,0.997671,0.999255,0.997952,0.998635,1.000000,...,1690.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999809,1.000000,0.999809,117.000000

In [11]:
min(df.exp_index), max(df.exp_index)

(400, 999)

In [14]:
other_df = read_sql_data_frame('../data/without_gambler/main.db')

In [15]:
min(other_df.exp_index), max(other_df.exp_index)

(0, 599)

In [16]:
data = pd.concat([df, other_df])
data = data.sort_values(by=['exp_index'])
data = data.reset_index(drop=True)
data = data.drop_duplicates()

In [17]:
data.to_csv('../data/numerical_experiments_without_gambler.csv')

In [18]:
data.describe()

,exp_index,first_opponent_q_1,first_opponent_q_2,first_opponent_q_3,first_opponent_q_4,second_opponent_q_1,second_opponent_q_2,second_opponent_q_3,second_opponent_q_4,mem_one_p_1,...,mem_one_cycle_length,reactive_p_1,reactive_p_2,reactive_p_3,reactive_p_4,evol_reactive_p_1,evol_reactive_p_2,evol_reactive_p_3,evol_reactive_p_4,reactive_cycle_length
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,499.500000,0.487114,0.507529,0.506513,0.496405,0.520443,0.500516,0.506080,0.493446,0.268355,...,3.575000,0.053408,0.100361,0.053408,0.100361,0.051514,0.026964,0.051514,0.026964,1.271000
std,288.819436,0.290850,0.286879,0.289602,0.291581,0.291042,0.282002,0.287517,0.287634,0.412731,...,53.461599,0.221819,0.220163,0.221819,0.220163,0.220051,0.087560,0.220051,0.087560,3.719327
min,0.000000,0.001186,0.000426,0.000538,0.001145,0.000254,0.000210,0.000403,0.000720,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,249.750000,0.225239,0.252376,0.254374,0.247647,0.261301,0.264528,0.262221,0.248554,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,499.500000,0.487043,0.522296,0.519162,0.478272,0.515770,0.498159,0.515061,0.487578,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,749.250000,0.735435,0.751023,0.763515,0.764454,0.774857,0.731178,0.749466,0.750983,0.570298,...,2.000000,0.000000,0.036286,0.000000,0.036286,0.000000,0.000000,0.000000,0.000000,1.000000
max,999.000000,0.998462,0.998575,0.999550,0.999766,0.998728,0.999653,0.999129,0.998740,1.000000,...,1690.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999809,1.000000,0.999809,117.000000

**with gambler**

In [20]:
gambler = read_sql_data_frame('../data/with_gambler/the_main.db')